export const confettiConfigurations = [
	{
		color: 'bg-confetti-yellow',
		left: '10%',
		delay: '0',
		name: 'confetti',
		duration: '5s',
		timing: 'ease-in-out',
		iteration: 'infinite',
	},
	{
		color: 'bg-confetti-cyan',
		left: '20%',
		delay: '-5s',
		name: 'confetti',
		duration: '5s',
		timing: 'ease-in-out',
		iteration: 'infinite',
	},
	{
		color: 'bg-confetti-red',
		left: '30%',
		delay: '-3s',
		name: 'confetti',
		duration: '5s',
		timing: 'ease-in-out',
		iteration: 'infinite',
	},
	{
		color: 'bg-confetti-yellow',
		left: '40%',
		delay: '-2.5s',
		name: 'confetti',
		duration: '5s',
		timing: 'ease-in-out',
		iteration: 'infinite',
	},
	{
		color: 'bg-confetti-cyan',
		left: '50%',
		delay: '-4s',
		name: 'confetti',
		duration: '5s',
		timing: 'ease-in-out',
		iteration: 'infinite',
	},
	{
		color: 'bg-confetti-red',
		left: '60%',
		delay: '-6s',
		name: 'confetti',
		duration: '5s',
		timing: 'ease-in-out',
		iteration: 'infinite',
	},
	{
		color: 'bg-confetti-yellow',
		left: '70%',
		delay: '-1.5s',
		name: 'confetti',
		duration: '5s',
		timing: 'ease-in-out',
		iteration: 'infinite',
	},
	{
		color: 'bg-confetti-cyan',
		left: '80%',
		delay: '-2s',
		name: 'confetti',
		duration: '5s',
		timing: 'ease-in-out',
		iteration: 'infinite',
	},
	{
		color: 'bg-confetti-red',
		left: '90%',
		delay: '-3.5s',
		name: 'confetti',
		duration: '5s',
		timing: 'ease-in-out',
		iteration: 'infinite',
	},
	{
		color: 'bg-confetti-yellow',
		left: '100%',
		delay: '-2.5s',
		name: 'confetti',
		duration: '5s',
		timing: 'ease-in-out',
		iteration: 'infinite',
	},
];
